### ISSUE TITLE
Reverse geocoding always fails `Geocoder::ResponseParseError`

### ISSUE THREAD

**Issue by MeijiRestored** [Freika/dawarich#333] opened 2024-10-16 17:04 UTC
**Describe the bug**
All reverse geocoding tasks fail with `Geocoder::ResponseParseError`.

**Version**
0.15.4

**Logs**
```
dawarich_sidekiq  | E, [2024-10-16T16:46:54.509796 #119] ERROR -- : Error performing ReverseGeocodingJob (Job ID: d570478e-375c-4b52-92d1-f9734bd4bdaa) from Sidekiq(reverse_geocoding) in 85.58ms: Geocoder::ResponseParseError (Geocoder::ResponseParseError):
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:186:in `raise_error'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:215:in `rescue in parse_json'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:208:in `parse_json'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:225:in `parse_raw_data'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:196:in `fetch_data'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/photon.rb:23:in `results'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/lookups/base.rb:46:in `search'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder/query.rb:11:in `execute'
dawarich_sidekiq  | /var/app/vendor/bundle/ruby/3.3.0/bundler/gems/geocoder-04ee2936a30b/lib/geocoder.rb:22:in `search'
dawarich_sidekiq  | /var/app/app/services/reverse_geocoding/points/fetch_data.rb:15:in `call'
dawarich_sidekiq  | /var/app/app/jobs/reverse_geocoding_job.rb:9:in `perform'
...
dawarich_sidekiq  | 2024-10-16T16:46:54.512Z pid=119 tid=kj3 class=ReverseGeocodingJob jid=0b5f9987fbe98fbf38ad7928 elapsed=0.5 INFO: fail
dawarich_sidekiq  | 2024-10-16T16:46:54.513Z pid=119 tid=kj3 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"reverse_geocoding","wrapped":"ReverseGeocodingJob","args":[{"job_class":"ReverseGeocodingJob","job_id":"d570478e-375c-4b52-92d1-f9734bd4bdaa","provider_job_id":null,"queue_name":"reverse_geocoding","priority":null,"arguments":["Point",334980],"executions":0,"exception_executions":{},"locale":"en","timezone":"Europe/Brussels","enqueued_at":"2024-10-16T16:35:11.591410395Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"0b5f9987fbe98fbf38ad7928","created_at":1729096511.5914497,"enqueued_at":1729097117.906883,"error_message":"Geocoder::ResponseParseError","error_class":"Geocoder::ResponseParseError","failed_at":1729096529.0304668,"retry_count":4,"retried_at":1729096836.6148896}}
dawarich_sidekiq  | 2024-10-16T16:46:54.513Z pid=119 tid=kj3 WARN: Geocoder::ResponseParseError: Geocoder::ResponseParseError
dawarich_sidekiq  | 2024-10-16T16:46:54.513Z pid=119 tid=kj3 WARN: app/services/reverse_geocoding/points/fetch_data.rb:15:in `call'
dawarich_sidekiq  | app/jobs/reverse_geocoding_job.rb:9:in `perform'
```
**Additional context**
Happens with both default geocoder (Nominatim) and self-hosted Photon instance (served over HTTPS from a remote server). It is happening only since the latest 0.15.4 update.

Here is an example query from my Photon instance in case it could be the issue (probably not since Nominatim fails as well):
`/reverse?lon=2&lat=50`
```json
{
    "features": [
        {
            "geometry": {
                "coordinates": [
                    1.9993273,
                    49.9994663
                ],
                "type": "Point"
            },
            "type": "Feature",
            "properties": {
                "osm_id": 297408537,
                "extent": [
                    1.9961878,
                    50.0094171,
                    1.9996089,
                    49.9881855
                ],
                "country": "France",
                "city": "Bettencourt-Rivière",
                "countrycode": "FR",
                "postcode": "80270",
                "county": "Somme",
                "type": "street",
                "osm_type": "W",
                "osm_key": "highway",
                "osm_value": "tertiary",
                "name": "Cavée du Quesnoy",
                "state": "Hauts-de-France"
            }
        }
    ],
    "type": "FeatureCollection"
}
```

**Comment by Tazmanian79** [comment] 2024-10-17 13:41
I can confirm this issue.  No more Reverse Geocoding after update to 0.15.4
I also use the photon api

**Comment by chrisl8** [comment] 2024-10-17 20:56
What does everyone have set for their `PHOTON_API_HOST` variable?

I know that I had to play around with variations such as:

`hostname`
`https://hostname`
`http://hostname:2322`
`hostname:2322`
`https://hostname:2322`
etc.

@Freika is this possibly because of using the new Geocoder library code https://github.com/Freika/dawarich/issues/300#issuecomment-2414606291 ?

It works great for me without `https` using:
`PHOTON_API_HOST=photon:2322`

Maybe now **only http** works and not **https**?

**Comment by chrisl8** [comment] 2024-10-17 21:39
@Freika  I can confirm that while it now works to contact a photon server via `http`, it seems unable to contact any photon server via `https` regardless of how I set up the `PHOTON_API_HOST` variable.

Maybe there is a way I haven't thought of yet?

Maybe my code PR for Geocoder actually doesn't work? I am not a Ruby developer so maybe I misunderstood what needed to be done. I had assumed if it my PR was accepted that someone else thought it was good, but maybe they had assumed I had tested it?

**Comment by chrisl8** [comment] 2024-10-18 14:21
> I am having the same issue. I am trying to use `Nominatim` with `REVERSE_GEOCODING_ENABLED: true` but no luck. Does the fix mentioned above also help with `Nominatim` users?

Yes, it should, as that is the same issue. Nominatim requires HTTPS and the current code is defaulting to HTTP with no method to force HTTPS.

Assuming my PR works and is accepted, it puts HTTPS back as the default, with an option to turn it off, so things should work again.

**Comment by Freika** [comment] 2024-10-19 16:47
Should be fixed in https://github.com/Freika/dawarich/releases/tag/0.15.5, let me know if you're still having this problem

**Closed by Freika** 2024-10-19 16:47 UTC
